services:
  server:
    image: node:alpine
    volumes:
      - ./server:/home/node/app
    working_dir: /home/node/app
    ports:
      - 127.0.0.1:3000:3000
    environment:
      PORT: 3000
    #command: sh -c "npm install && npm run dev:windows"
    command: sh -c "npm install && npm run dev"
